// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApe7MZKq1l2Ppayp0rz3kXpWC-oqpehw',
    appId: '1:1042613439726:web:2745882488fd6034e777ff',
    messagingSenderId: '1042613439726',
    projectId: 'chat-app-d37a5',
    authDomain: 'chat-app-d37a5.firebaseapp.com',
    databaseURL: 'https://chat-app-d37a5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d37a5.appspot.com',
    measurementId: 'G-DJNLL5Y64M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDya-yS1nd7b2vVk9sZUtrJA-XrB_uk1Hs',
    appId: '1:1042613439726:android:8dc1ef566a01dc2be777ff',
    messagingSenderId: '1042613439726',
    projectId: 'chat-app-d37a5',
    databaseURL: 'https://chat-app-d37a5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d37a5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBj9MET5RRrfwqYVl7w52I7Lg6rzo2UP9I',
    appId: '1:1042613439726:ios:43c4400335d012d6e777ff',
    messagingSenderId: '1042613439726',
    projectId: 'chat-app-d37a5',
    databaseURL: 'https://chat-app-d37a5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d37a5.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBj9MET5RRrfwqYVl7w52I7Lg6rzo2UP9I',
    appId: '1:1042613439726:ios:596978fa2159fa53e777ff',
    messagingSenderId: '1042613439726',
    projectId: 'chat-app-d37a5',
    databaseURL: 'https://chat-app-d37a5-default-rtdb.firebaseio.com',
    storageBucket: 'chat-app-d37a5.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
